<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	defined('BASE_URL')	|| define('BASE_URL', Zend_Controller_Front::getInstance()->getBaseUrl());?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <!-- Bootstrap Styles-->
    <link href="<?php echo BASE_URL; ?>/assets/admin/layout/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link href="<?php echo BASE_URL; ?>/assets/admin/layout/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="<?php echo BASE_URL; ?>/assets/admin/layout/css/custom-styles.css" rel="stylesheet" />
    <!-- Google Fonts-->
</head>
<?php $session_user=new Zend_Session_Namespace('auth');
  $request=Zend_Controller_Front::getInstance()->getRequest();
  $url_index_product =  $this->url(array('module'=>'product','controller'=>'index','action'=>'index'));
  $url_index_sales =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'index'));
  $url_index_purchase =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'));
  $url_index_paymet =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'index'));
  $url_index_user =  $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'));
  $url_index_report_product =  $this->url(array('module'=>'report','controller'=>'product','action'=>'index'));
  $url_index_report_sales =  $this->url(array('module'=>'report','controller'=>'index','action'=>'index'));
  ?>
  <style>
     a,a:hover{color:#fff;}
</style> 
<body>
    <div id="wrapper">
        
        <!--/. NAV TOP  -->
        
        <!-- /. NAV SIDE  -->
        
                <!-- /. ROW  -->
                <div class="row">
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-body">
                                <i class="fa fa-shopping-cart fa-5x"></i>
                                <?php 
                                      //$dbtable = new Product_Model_DbTable_DbProduct();
                                      //$product= $dbtable->getProductName($session_user->user_id);
                                ?>
                                
                                <h3>
                                <?php // $i=0;foreach ($product as $values){$i++;
					      //count($values['id']);}echo $i;?></h3>
                            </div>
                            <a href="<?php echo $url_index_product;?>">
                            <div class="panel-footer back-footer-green">
                              <?php echo $tr->translate("PRODUCT");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue">
                            <div class="panel-body">
                                <i class="fa fa-shopping-cart fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_sales;?>">
                            <div class="panel-footer back-footer-blue">
                                <?php echo $tr->translate("SALES");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-red">
                            <div class="panel-body">
                                <i class="fa fa-shopping-cart fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_purchase;?>">
                            <div class="panel-footer back-footer-red">
                               <?php echo $tr->translate("PURCHASING");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-brown">
                            <div class="panel-body">
                                <i class="fa fa-money fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_paymet;?>">
                            <div class="panel-footer back-footer-brown">
                                <?php echo $tr->translate("PAYMENT");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-body">
                                <i class="fa fa-users fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_user;?>">
                            <div class="panel-footer back-footer-green">
                                <?php echo $tr->translate("USER");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green">
                            <div class="panel-body">
                                <i class="fa fa-bar-chart-o fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_report_product;?>">
                            <div class="panel-footer back-footer-green">
                                <?php echo $tr->translate("MENU_REPORT_PRODUCT");?>
                            </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue">
                            <div class="panel-body">
                                <i class="fa fa-bar-chart-o fa-5x"></i>
                                <h3></h3>
                            </div>
                            <a href="<?php echo $url_index_report_sales;?>">
                            <div class="panel-footer back-footer-blue">
                                <?php echo $tr->translate("MENU_REPORT");?>
                            </div>
                            </a>
                        </div>
                    </div>
                </div>


                
                <!-- /. ROW  -->

                
              
                <!-- /. ROW  -->
				<footer><p></p></footer>
            
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->

</body>

</html>