<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'purchasereceivelist','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'purchasereceivelist','action'=>'index'));
?>
<title><?php echo $tr->translate("ADD_PURCAHSE_RECEIVE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_RECEIVE")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" class="form-horizontal" novalidate="novalidate" action="" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("VENDOR_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("v_name");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("LOCATION_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('LocationId');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ORDER_DATE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<i class="fa fa-calendar"></i><?php echo $form->getElement("order_date");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php  echo $tr->translate("DATE_IN");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<?php echo $form->getElement("date_in");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("STATUS");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("purchase_status");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("PO_NUM");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("txt_order"); ?></div>
							</div>
						</div>
						<div class="form-group" >
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_NO");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("invoice_no"); ?></div>
							</div>
						</div>
			
						
	<ul class="nav nav-tabs ">
		<li class="active">
			<a href="#tab_5_1" data-toggle="tab">
			<?php echo $tr->translate("PRODUCT_IN_STOCK");?> </a>
		</li>
		<li class="">
			<a href="#tab_5" data-toggle="tab">
			<?php echo $tr->translate("PRODUCT_LEAVE_STOCK");?> </a>
		</li>
	</ul>	
	<div class="tab-content">
			<div class="tab-pane active" id="tab_5_1">
	            <div class="portlet-body form">			
	 <!--  	select product  -->	
						<div class="form-group">
						<div class="col-md-12">
							<label class="control-label col-md-1 col-lg-1">
								<button type="button" class="btn red delete col-md-12">
									<i class="fa fa-barcode"></i>
									<span><?php echo $tr->translate("SCAN");?></span>	
								</button>
							</label>
							<label class="control-label col-md-8">
								<select data-placeholder="Select..." readonly="readonly" class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();getBlockBysites();" >
								<?php echo $this->items; ?>
								</select>
							</label>
							<label class="control-label col-md-2 col-lg-2 col-sm-12">
								<button type="button" onclick="popupProduct();" class="btn red delete col-md-12">
									
									<span>&nbsp;&nbsp;<?php echo $tr->translate("ADD_NEW_ITEM");?></span>
								</button>
							</label>
							<label class="control-label col-md-1 col-lg-1 col-sm-12">
								<button type="button" class="btn red delete col-md-12">
							  
									<input type="hidden" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;<?php //echo $tr->translate("FREE");?></span>
								 
								</button>
							</label>
						</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
								<!--<th><?php echo $tr->translate("FREE");?></th>  -->
									<th><?php echo $tr->translate("QTY_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									
									<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
									<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
								<!--<th><?php echo $tr->translate("BLOCK");?></th>-->
							</tr>
						 </table>
						 <input type="text" id="identity" name="identity" />
								
					</div>
						
						
	<!-- the end select product  -->			
				</div>
			</div>	
			<div class="tab-pane " id="tab_5">
         	 <div class="portlet-body form">
	<!-- select product Leave Stock  -->	
						
						<div class="form-group">
						<div class="col-md-12">
							<label class="control-label col-md-1 col-lg-1">
								<button type="button" class="btn red delete col-md-12">
									<i class="fa fa-barcode"></i>
									<span>Scan </span>	
								</button>
							</label>
							<label class="control-label col-md-8">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item_leave" name="add_item_leave" Onchange="getItemOrderLeaveProduct();getBlockBysite();" >
								<?php echo $this->items_leave; ?>
								</select>
							</label>
							<label class="control-label col-md-2 col-lg-2 col-sm-12">
								<button type="button" onclick="popupProduct();" class="btn red delete col-md-12">
									
									<span>&nbsp;&nbsp;បន្ថែមមុខទំនិញថ្មី</span>
								</button>
							</label>
							<label class="control-label col-md-1 col-lg-1 col-sm-12">
								 <button type="button" class="btn red delete col-md-12">
									<!--<input type="checkbox" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;Free</span>
									-->
								</button> 
							</label>
						</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_leave_product" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<!--<th><?php echo $tr->translate("FREE");?></th>-->
									<th><?php echo $tr->translate("QTY_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									<th><?php echo $tr->translate("UNIT_LABEL");?></th>
									<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
									<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
								<!--<th><?php echo $tr->translate("BLOCK");?></th> -->
									<th><?php echo $tr->translate("JOb");?></th>
							</tr>
						 </table>
						 <input type="text" id="leave_stock_identity" name="leave_stock_identity" />
								
					</div>
					<!-- 
						 <div class="form-group">
						    <label class="control-label col-md-2"><?php //echo $tr->translate("CURRENCY_TYPE");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("currency");?>
								</div>
							</div>
							
							
								<label class="control-label col-md-2"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("totalAmoun_l");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_name");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_number");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("dis_value_l");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ថ្ងៃត្រូវចេញសែក");?><span class="required">
							 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("date_issuecheque");?>
								</div>
							</div>
							<label class="control-label col-md-2">សាច់ប្រាក់សរុប​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total_l");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("paid");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid_l");?>
								</div>
							</div>
							
							<label class="control-label col-md-1"><?php echo $tr->translate("BALANCE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-1">
								<div class="input-icon right">
								<?php echo $form->getElement("remain_l");?>
								</div>
							</div>
						</div>
						 -->
		<!-- the end product Leave Stock  -->
	           </div>
	         </div>
	    <!-- the all total  paid and discount  -->    
	             <div class="form-group">
						    <label class="control-label col-md-2"><?php //echo $tr->translate("CURRENCY_TYPE");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("currency");?>
									<?php echo $form->getElement("price_product");?>
									<?php echo $form->getElement("price_jobtype");?>
								</div>
							</div>
							
							
								<label class="control-label col-md-2"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("totalAmoun");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_name");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php //echo $form->getElement("payment_number");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("dis_value");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ថ្ងៃត្រូវចេញសែក");?><span class="required">
							 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("date_issuecheque");?>
								</div>
							</div>
							<label class="control-label col-md-2">សាច់ប្រាក់សរុប​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("paid");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>
							
							<label class="control-label col-md-1"><?php echo $tr->translate("BALANCE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-1">
								<div class="input-icon right">
								<?php echo $form->getElement("remain");?>
								</div>
							</div>
						</div>
						<!-- the End all total  paid and discount  -->    
	</div>
						<div class="form-group">
						
						    <div class="col-md-4">
								<a href="<?php echo $this->baseUrl();?>/purchase/index/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							
							<div class="col-md-4">
								<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							
							<div class="col-md-4">
								<div class="input-icon right">
									<button type="submit" name="btnsave_print" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>
								</div>
							</div>
							
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$('#frm').submit(function() {
//aa = $("#frm").validationEngine();
//alert(JSON.stringify(aa));
//return false;
	customer_id=$("#v_name").val();
	if(customer_id=='' || customer_id==-1){
		alert("Please select vendor name");
		$('#v_name').select2('open');
		return false;	
	}
	/*
	identity =$("#leave_stock_identity").val();
	if(identity=='' || identity==-1){
		alert("Please add product row");
		$('#add_item').select2('open');
		return false;
	} 
	*/
});
</script>
<?php $frm_product= $this->form;?>
<div id="productpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PRODUCT");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php //echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmproduct" name="frmproduct" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("ITEM");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("name");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<span class="required">
							        <?php echo $tr->translate("ITEM_CODE");?>
						    </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("pro_code");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("BARCODE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("barcode");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SERIAL_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("serial");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("BRAND_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("brand");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("MODEL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("model");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CATEGORY");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("category");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SIZE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("size");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("COLOR");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("color");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SIZE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("size");?>
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("measure");?><span class="required">
								</span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("measure");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("qty_unit");?>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("LABEL");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<?php echo $frm_product->getElement('label');?>
							</div>
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("description");?><span class="required">
								</span>
							</label>
							<div class="col-md-10">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm_product->getElement("description");?>
								</div>
							</div>
						</div>
						
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" Onclick="addProduct();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRODUCT")?> </button>
						</label>
					</div>
				</div>
				</form>
			   </div>
		     </div>
	        </div>
          </div>
          </div>
        </div>
    </div>
 </div>
<?php $frm_vendor= $this->form_vendor;?>
<div id="dialogvendor" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
               <div class="modal-content">
               		<div class="portlet box blue ">
               		<div class="modal-header">
                                   <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                     <h4 class="modal-title center"><?php echo $tr->translate("ADD_VENDOR");?></h4>
                                    <div class="portlet-body form">
                                         <form id="frmvendor" name="frmvendor" method="post">
                                            <div class="form-body">
                                                <div class="form-group col-md-6">
                                                    <label class="control-label "><?php echo $tr->translate("SUPPLIYER_NANE");?></label>
                                                    <?php echo $frm_vendor->getElement("vendor_name");?></div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label"><?php echo $tr->translate("COM_PHONE");?></label>
                                                    <?php echo $frm_vendor->getElement("com_phone");?></div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label"><?php echo $tr->translate("CON_NAME");?></label>
                                                    <?php echo $frm_vendor->getElement("txt_contact_name");?></div>
                                                <div class="form-group col-md-6">
                                                    <label class="control-label"><?php echo $tr->translate("CON_NUM");?></label>
                                                    <?php echo $frm_vendor->getElement("v_phone");?></div>
                                                <div class="form-group">
                                                    <label class="control-label"><?php echo $tr->translate("VENDOR_ADD");?></label>
                                                    <?php echo $frm_vendor->getElement("txt_address");?></div>
                                               <div class="form-group">
                                                    <label class="control-label"><?php echo $tr->translate("EMAIL");?></label>
                                                    <?php echo $frm_vendor->getElement('txt_mail');?></div>
                                               <div class="form-group">
                                                    <label class="control-label"><?php echo $tr->translate("NOTE");?></label>
                                                    <?php echo $frm_vendor->getElement('vendor_note');?></div>
                                               <div class="form-group">
                                                	<label class="control-label"></label><input onclick="addNewVendor();" id="btn_add" type="button" class="btn default blue col-md-12" value="<?php echo $tr->translate("ADD_NEW");?>" />
                                               </div>
                                            </div>
                               </form>
                      </div>
                 </div>
           </div>
        </div>
    </div>
 </div>
<script>
function getReadOnly(){
	//$('#add_item').attr('readonly',true);
	$('#add_item').attr('disabled',true);
	$('#add_item_leave').attr('disabled',true);
}
function getSuppliyer(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
<?php $url_add_vendor =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'addvendor')); ?>
function addNewVendor(){
	var v_name  = $("#vendor_name").val();	
	if(v_name==''){
		return false;
	}	
	$.ajax({
        url: "<?php echo $url_add_vendor;?>",
        type: "post",
        data: $('#frmvendor').serialize(),
        success: function(data){
			alert(222);
            val = $.parseJSON(data);
		      val = $.parseJSON(data);
		    $('#v_name').append($("<option></option>").attr("value",val['vid']).attr("selected",true).text(v_name));                       
			$("#v_name").select2();
		    $('#dialogvendor').modal('hide');
        },
        error:function(e){
            alert("faile insert");
          
        }
    });
}
function popupProduct(){
	$('#productpopup').modal('show');
}
<?php $url_add_new =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-newproudct')); ?>
function addProduct(){
		branch_id = $("#LocationId").val();
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: $('#frmproduct').serialize()+'&'+$.param({ 'branch_id': branch_id}),
	        success: function(data){
		      data = $.parseJSON(data);
		      $('#add_item').append($("<option></option>").attr("value",data['pro_id']).attr("selected",true).text($("#name").val()));                       
			  $("#add_item").select2();
		      $('#productpopup').modal('hide');
			  addRow(data['pro_id']);
			  $('#item_id_'+index5).append($("<option></option>").attr("value",data['pro_id']).attr("selected",true).text($("#name").val()));                       
				 $("#item_id_"+index5).select2();
				 $('#qty'+index5).val(1);
	        },
	        error:function(){
	           
	        }
	    });	
}

///ajax select fileter block by site  
<?php $url_block = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'get-block-bysites')); ?>
function getBlockBysite(){
	branch_id = $("#LocationId").val();
	$.ajax({
        url: "<?php echo $url_block;?>",
        type: "post",
        data:{'branch_id':branch_id},
        success: function(data){
	     so = $.parseJSON(data);
	       //alert(so);
		        var identity = $('#leave_stock_identity').val();
			 	var arrays = identity.split(',');
			 	for(var k=1;k<=arrays.length;k++){
			 		
			 		 if(so !=""){
			 		  $('option', '#block_id_l_'+k).remove();
				 	  for(i=0;i<so.length;i++){  
					  		 $('#block_id_l_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].name));                   
						  	 $("#block_id_l_"+k).select2();
					  }
			 		}else{
				 		
			 			//$('option', '#block_id_'+k).append($("<option></option>").attr("value","").text(""));
			 			$('option', '#block_id_l_'+k).remove();
			 			$("#block_id_l_"+k).select2();
			 		 	$('#block_id_l_'+k).append('<option value="-1">Add New Block</option>');
			 		 
			 		}
			 	}
        },
        error:function(){
           
        }
    });	
}

///ajax select fileter block by site  
<?php $url_blocks =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'get-block-bysites')); ?>
function getBlockBysites(){
		branch_id = $("#LocationId").val();
		$.ajax({
	        url: "<?php echo $url_blocks;?>",
	        type: "post",
	        data:{'branch_id':branch_id},
	        success: function(data){
		     so = $.parseJSON(data);
		       
			        var identity = $('#identity').val();
				 	var arrays = identity.split(',');
				 	for(var k=1;k<=arrays.length;k++){
				 		
				 		 if(so !=""){
				 		  $('option', '#block_id_'+k).remove();
					 	  for(i=0;i<so.length;i++){  
						  		 $('#block_id_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].name));                   
							  	 $("#block_id_"+k).select2();
						  }
				 		}else{
					 		
				 			//$('option', '#block_id_'+k).append($("<option></option>").attr("value","").text(""));
				 			$('option', '#block_id_'+k).remove();
				 			$("#block_id_"+k).select2();
				 		 	$('#block_id_'+k).append('<option value="-1">Add New Block</option>');
				 		 
				 		}
				 	}
		        
	        },
	        error:function(){
	           
	        }
	    });	
		getBlockBysite();
}
 

var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
//var index=1;
function addRow(item_id) {
	index5++; //var first = index5;
	//index=index+1;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index5+'</td>';
	template+='<td width="30%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<input type="hidden" onkeyup="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+='<td width="10%"><select class="form-control select2me"  id="block_id_'+index5+'" name="block_id_'+index5+'" ><option>'+getBlockBysites()+'</option></select>'+inp+'</td>';
	
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);

	getQtyById(index5);

	if(free.checked){
		$("#pricefree_"+index5).attr({checked:'checked'});  
		$("#price"+index5).val(0);
		$("#price"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).attr('readonly','readonly');
		$("#dis-value"+index5).val(0);
	}
	else{
		//$("#dis-value"+index5).val(0);
		//$('#dis_value').val(0);
		$('#global_disc').val(0);
		//getCurrentPrice(index5);
		$("#paid").val(0);
	}
	 $("#item_id_"+index5).select2();
	 $("#block_id_"+index5).select2();
	$("#row_order_0").remove();
}

//old addrows 
$(document).ready(function() {
	oldAddRow();
	oldAddRowLeave();
	//netTotal();
	getReadOnly();
});
function oldAddRow() {
	index5=0;
	var template;
	var option5 = '<?php echo $this->items;?>';
	<?php if(!empty($this->rs_p_detail)) {
		foreach($this->rs_p_detail AS $i=>$r){?>
	index5++; 
	index=index+1;
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="" src="<?php //echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index5+'</td>';
	template+='<td width="30%"> <input type="text" class="form-control "   id="item_id_'+index5+'" name="item_id_'+index5+'" > <select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_ids_'+index5+'" name="item_ids_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<input type="hidden" onkeyup="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	//template+='<td width="10%"><select class="form-control select2me"  id="block_id_'+index5+'" name="block_id_'+index5+'" ><option>'+getBlockBysites()+'</option></select>'+inp+'</td>';
	template+="</tr>";
	$('#table_order').append(template);
	
	$("#item_id_"+index5).val("<?php echo $r['pro_id'];?>");
	$("#item_ids_"+index5).val("<?php echo $r['pro_id'];?>");
	$('#item_ids_'+index5).attr('disabled',true);
	
	$("#qty"+index5).val("<?php echo $r['qty_order'];?>");
	$("#qty_unit_"+index5).val("<?php echo $r['qty_unit'];?>");
	$("#qty_per_unit_"+index5).val("<?php echo $r['qty_detail'];?>");
	$("#price"+index5).val("<?php echo $r['price'];?>");
	$("#total"+index5).val("<?php echo $r['sub_total'];?>");
	$("#dis_value"+index5).val("<?php echo $r['disc_value'];?>");
	$("#oldprice_"+index5).val("<?php echo $r['price'];?>");

	//$('#block_id_'+index5).attr('disabled',true);
	 
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	
	$("#row_order_0").remove();
		<?php } }?>
}

///funciton add row leave product 
var index = 0;num=0;
var option6 = '<?php echo $this->items_leave; ?>';
var job='<?php echo $this->jobtype; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
 
function addRowLeave(item_id) {
	index++; //var first = index5;
	 
	for(i=1; i<index; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_leave_id_"+i).val());
	}
	template='<tr id="row_order_leave_'+index+'" style="height:33px;">';
	var inp = '';
	if(index == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecordLeave('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index+'</td>';
	template+='<td width="30%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index + ');" id="item_leave_id_'+index+'" name="item_leave_id_'+index+'" ><option>'+option6+'</option></select>'+inp+'</td>';
	template+='<input type="hidden" onkeyup="getPriceFree('+index+')" id="pricefree_l_'+index+'" name="pricefree_l_'+index+'"/>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_l_'+index+'" name="qty_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_l_'+index+'" name="qty_per_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePriceLeave('+index+')" class="form-control" required="1" id="qty_l_'+index+'" name="qty_l_'+index+'"/></td>';

	template+='<td ><input type="text" onkeyup="calculatePriceLeave('+index+')" required="1" class="validate[required,custom[number]] input form-control" id="price_l_'+index+'" name="price_l_'+index+'" /><input type="hidden" id="oldprice_'+index+'" name="oldprice_'+index+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePriceLeave('+index+')" value="0" id="dis_value_l_'+index+'" name="dis_value_l_'+index+'" class="form-control" /><input type="hidden" id="olddis_value_'+index+'" name="olddis_value_'+index+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index+'" name="real-value'+index+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total_l_'+index+'" name="total_l_'+index+'" /></span></td>';
	template+='<td width="10%"><select class="form-control select2me"  id="block_id_l_'+index+'" name="block_id_l_'+index+'" ><option>'+getBlockBysite()+'</option></select>'+inp+'</td>';
	template+='<td width="6%"><select class="form-control select2me"   id="job_id_'+index+'" name="job_id_'+index+'" ><option>'+job+'</option></select>'+inp+'</td>';
	
	template+="</tr>";
	$('#table_leave_product').append(template);
	if($('#leave_stock_identity').val()!="") {
		var identity = $('#leave_stock_identity').val();
		$('#leave_stock_identity').val(identity+','+index);
	} else {$('#leave_stock_identity').val(index);}
	$("#item_leave_id_"+index).val(item_id);

	getQtyByIds(index);

	if(free.checked){
		$("#pricefree_"+index).attr({checked:'checked'});  
		$("#price"+index).val(0);
		$("#price"+index).attr('readonly','readonly');
		$("#dis-value"+index).attr('readonly','readonly');
		$("#dis-value"+index).val(0);
	}
	else{
		//$("#dis-value"+index5).val(0);
		//$('#dis_value').val(0);
		$('#global_disc').val(0);
		//getCurrentPrice(index);
		$("#paid").val(0);
	}
	$("#block_id_l_"+index).select2();
	 $("#item_leave_id_"+index).select2();
	 
	 $("#job_id_"+index).select2();
	$("#row_order_0").remove();
}

///oldAddRowLeave 
function oldAddRowLeave(item_id){
	
	index=0;
	for(i=1; i<index; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	 
	var template;
	var option6 = '<?php echo $this->items_leave;?>';
	<?php if(!empty($this->rs_job_detail)) {
		foreach($this->rs_job_detail AS $i=>$r){?>
		index++; 
		template='<tr id="row_order_leave_'+index+'" style="height:33px;">';
		var inp = '';
		if(index == 1) {
			template+='<td >&nbsp;</td>';
		} else {
			template+='<td ><img  src="<?php //echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		}
	
	template+='<td  width="2%">'+index+'</td>';
	template+='<td width="25%">  <input type="text" class="form-control "   id="item_leave_id_'+index+'" name="item_leave_id_'+index+'" > <select class="form-control select2me" Onchange="ShowPopupProduct('+ index + ');" id="item_leave_ids_'+index+'" name="item_leave_ids_'+index+'" ><option>'+option6+'</option></select>'+inp+'</td>';
	template+='<input type="hidden" onkeyup="getPriceFree('+index+')" id="pricefree_l_'+index+'" name="pricefree_l_'+index+'"/>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_l_'+index+'" name="qty_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_l_'+index+'" name="qty_per_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePriceLeave('+index+')" class="form-control" required="1" id="qty_l_'+index+'" name="qty_l_'+index+'"/></td>';
	template+='<td ><input type="text"   class="form-control" required="1" id="label_l_'+index+'" name="label_l_'+index+'"/></td>';
    
	template+='<td ><input type="text" onkeyup="calculatePriceLeave('+index+')" required="1" class="validate[required,custom[number]] input form-control" id="price_l_'+index+'" name="price_l_'+index+'" /><input type="hidden" id="oldprice_'+index+'" name="oldprice_'+index+'"/></td>';

	template+='<td  width="5%"><input type="text" onkeyup="calculatePriceLeave('+index+')" value="0" id="dis_value_l_'+index+'" name="dis_value_l_'+index+'" class="form-control" /><input type="hidden" id="olddis_value_'+index+'" name="olddis_value_'+index+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index+'" name="real-value'+index+'" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total_l_'+index+'" name="total_l_'+index+'" /></span></td>';
//	template+='<td width="10%"><select class="form-control select2me"  id="block_id_l_'+index+'" name="block_id_l_'+index+'" ><option>'+getBlockBysite()+'</option></select>'+inp+'</td>';
	template+='<td width="6%"> <input type="text" class="form-control "   id="job_id_'+index+'" name="job_id_'+index+'" > <select class="form-control select2me"   id="job_ids_'+index+'" name="job_ids_'+index+'" ><option>'+job+'</option></select>'+inp+'</td>';
	
	template+="</tr>";
	$('#table_leave_product').append(template);
	
	$("#item_leave_id_"+index).val("<?php echo $r['pro_id'];?>");
	$("#item_leave_ids_"+index).val("<?php echo $r['pro_id'];?>");
	$('#item_leave_ids_'+index).attr('disabled',true);
	
	$("#qty_l_"+index).val("<?php echo $r['qty_order'];?>");
	//$("#label_l_"+index).val("<?php //echo $r['unit_label'];?>");
	$("#qty_unit_"+index).val("<?php echo $r['qty_unit'];?>");
	$("#qty_per_unit_"+index).val("<?php echo $r['qty_detail'];?>");
	$("#price_l_"+index).val("<?php echo $r['price'];?>");
	$("#total_l_"+index).val("<?php echo $r['sub_total'];?>");
	$("#dis_value_l_"+index).val("<?php echo $r['disc_value'];?>");
	$("#oldprice_"+index).val("<?php echo $r['price'];?>");
	//$("#block_id_l_"+index).val("<?php //echo $r['block_id'];?>");
	$("#job_id_"+index).val("<?php echo $r['job_type'];?>");
	$("#job_ids_"+index).val("<?php echo $r['job_type'];?>");
	$("#job_ids_"+index).attr('disabled',true);
	
	if($('#leave_stock_identity').val()!="") {
		var identity = $('#leave_stock_identity').val();
		$('#leave_stock_identity').val(identity+','+index);
	} else {$('#leave_stock_identity').val(index);}
	//$("#item_leave_id_"+index).val(item_id);
	 
 
	getQtyByIds(index);
	
	$("#row_order_0").remove();
		<?php } }?>
}


<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){//use
			item_id=$("#item_id_"+index).val();
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();
				branch_id = $("#LocationId").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							 
							item_qty = $.parseJSON(data);			
							main_qty =$("#qty_unit_"+index).val();
							detail_qty =  $("#qty_per_unit_"+index).val();
							$("#current_qty"+index).val(item_qty.qty);
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty"+index).val(total_qty.toFixed(3));

							//getProductPrice(item_id,index);
						},
						error:function(e){
							//alert(e);
						}
				});
			}
}

///get qty set order qty 
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyByIds(index){//use
			item_id=$("#item_leave_id_"+index).val();
				qty_unit=$("#qty_unit_l_"+index).val();
				qty_per_unit=$("#qty_per_unit_l_"+index).val();
				branch_id = $("#LocationId").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty_l_"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							
							item_qty = $.parseJSON(data);	
							 
							main_qty =$("#qty_unit_l_"+index).val();
							detail_qty =  $("#qty_per_unit_l_"+index).val();
							$("#current_qty_l_"+index).val(item_qty.qty);
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty_l_"+index).val(total_qty.toFixed(3));
							$("#label_l_"+index).val(item_qty.unit_label);
							
							//getProductPrice(item_id,index);
						},
						error:function(e){
							//alert(e);
						}
				});
			}
}

function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		$('#productpopup').modal('show');
	}
	addRow(item_ids);
	$("#add_item").val("");
}
///function leave product 
function getItemOrderLeaveProduct(){
	 
	item_ids=$("#add_item_leave").val();
	$('#add_item_leave').val('').trigger("liszt:updated");
	if(item_ids==-1){
		$('#productpopup').modal('show');
	}
	addRowLeave(item_ids);
	$("#add_item_leave").val("");
}

var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}

function deleteRecordLeave(index) {
	var identity = $('#leave_stock_identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#leave_stock_identity').val(strings);
	$("#row_order_leave_"+index).remove();
	netTotal();
}

function netTotal() {//use
	var cur_type = $('#currency').val();
	
	var netTotal=0;
	var rowId = $('#identity').val();
	if(rowId !=''){
		var rowIDArray = rowId.split(',');
		var status = $('#status').val();
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += Number($('#total'+rowIDArray[n]).val());
		}
	}else{
		netTotal=0;
	}
	
	///sum total amount type job 
	var netTotals=0;
	var rowIds = $('#leave_stock_identity').val();
	if(rowIds!=''){
		var rowIDArrays = rowIds.split(',');
		var status = $('#status').val();
		for(var n = 0; n < rowIDArrays.length; n++) {
			netTotals += Number($('#total_l_'+rowIDArrays[n]).val());
		}
	}else{
			netTotals=0;
	}
	 
	var result =(parseFloat(netTotal)+parseFloat(netTotals));
	$('#totalAmoun').val(result.toFixed(2));
	$("#price_product").val(netTotal.toFixed(2));
	$("#price_jobtype").val(netTotals.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = $('#dis_value').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
	$('#paid').val(totalpayment);
		doRemain();
}
///calcual leave discount 
function netTotals() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#leave_stock_identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total_l_'+rowIDArray[n]).val());
	}
	$('#totalAmoun_l').val(netTotal.toFixed(2));
	calculateDiscounts();
}
function calculateDiscounts(){//use
	var discountValue = $('#dis_value_l').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun_l").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total_l').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun_l").val();
				totalpayment = alltotal - discountValue;
				$('#all_total_l').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun_l").val();
		totalpayment = alltotal - 0;
		$('#all_total_l').val(totalpayment);
	}
	$('#paid_l').val(totalpayment);
		doRemains();
}

function CalcualteTax() {
	$('#status').val();
}
function doRemain() {
	var all_total = parseFloat($('#all_total').val());
	var paid = parseFloat($('#paid').val());
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}
	
}

function doRemains() {
	var all_total = parseFloat($('#all_total_l').val());
	var paid = parseFloat($('#paid_l').val());
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain_l').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain_l').val(remain.toFixed(2));
	}
	
}

function totalQty(index){
	calculatePrice(index);
	getQtyById(index);

	$("#price"+index).val('');
}
///qty leave product 
function totalQtys(index){
	calculatePriceLeave(index);
	getQtyByIds(index);

	$("#price_l_"+index).val('');
}

function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
		
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));		
		}
		netTotal();
}
///function get price live 
function calculatePriceLeave(index) {
	
	var qty = $('#qty_l_'+index).val();
	var price = $('#price_l_'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value_l_'+index).val();
	if(ds.length!=0){
		
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total_l_'+index).val(after_discount.toFixed(2));
		}else{
		
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value_l_'+index).val(0);
				after_discount = total;
			}
			$('#total_l_'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
		$('#total_l_'+index).val(parseFloat(total).toFixed(2));		
		}
	//netTotals();
	netTotal();
	//calculatePrice();
	
	
}

 var record_id = 1;
function ShowPopupProduct(product_id){
	item_id = $("#item_id_"+ product_id).val();
	record_id = product_id;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(product_id);
	}
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		$('#popup_location').modal('show');
	  }	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
<?php $url_code =  $this->url(array('module'=>'purchase','controller'=>'index','action'=>'check-purchaseno')); ?>
function CheckPOInvoice(){
				pur_no=$("#txt_order").val();
				if(pur_no=="" || pur_no ==null){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'pur_no':pur_no},
						success: function(data){
							value = $.parseJSON(data);
							if(value=="" || value==null){
							}
							else{
								alert("Invoice number is exist !");
								$("#txt_order").css("border-color","red");
								$("#txt_order").val("");
							}
						},
						error:function(){
						}
					});
				}	
}
</script>	