<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'index','action'=>'index'));
	$url_new = $this->url(array('module'=>'sales','controller'=>'index','action'=>'add'));
?>
<title><?php echo $tr->translate("ADD_SALESORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_SALESORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- Block FORM-->
				<form id="frm" action="" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php  echo $tr->translate("SALE_AGENT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("saleagent_id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("QUOATATION_DATE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<i class="fa fa-calendar"></i><?php echo $form->getElement("order_date");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("SALE_ORDER");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("txt_order"); ?>
								</div>
							</div><label class="control-label col-md-2"><?php echo $tr->translate("CURRNECY_TYPE");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("currency");?>
								</div>
							</div>
						</div>
						<div class="form-group">
						    <label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch_id');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									
								</div>
							</div>
						</div>
						<!-- Close Form  -->
						<!-- Block Head Tap-->
						<ul class="nav nav-tabs ">
							<li class="active">
								<a href="#tab_5_1" data-toggle="tab">
								<?php echo $tr->translate("PRODUCT_IN_STOCK");?> </a>
							</li>
							<li class="">
								<a href="#tab_5" data-toggle="tab">
								<?php echo $tr->translate("PRODUCT_LEAVE_STOCK");?> </a>
							</li>
						</ul>
						<!-- Close Head Tap -->
						<!-- Block Contant Tap -->
						<div class="tab-content">
							<!-- Block Contant Tap one-->
							<div class="tab-pane active" id="tab_5_1">
								<div class="portlet-body form">			
									<div class="form-group">
										<div class="col-md-12">
											<label class="control-label col-sm-2" style="text-align:center;">
												<button type="button" class="btn red delete ">
													<i class="fa fa-barcode"></i>
													<span><?php echo $tr->translate("SCAN");?></span>	
												</button>
											</label>
											<label class="control-label col-sm-10">
												<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();getProuductInstock();" class="form-select" >
												   
												<?php //echo $this->items; ?>
												 
												</select>
											</label>
										</div>
									</div>
										<div class="portlet-body">
											<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
												<tr height="33px">
													<th><?php echo $tr->translate("DEL");?></th>
													<th><?php echo $tr->translate("NUM");?></th>
													<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
													<th style="white-space:nowrap;"><?php echo $tr->translate("CURR_QTY");?></th>
													<th><?php echo $tr->translate("QTY_UNIT");?></th>
													<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
													<th><?php echo $tr->translate("QTY_ORDER");?></th>
													<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
													<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
													<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
													<th><?php echo $tr->translate("BLOCK");?></th>
												</tr>
											</table>
											<input type="hidden" id="identity" name="identity" />	
										</div>			
								</div>
							</div>	
							<!-- Close Contant Tap one-->
							<!-- Block Contant Tap Two-->
							<div class="tab-pane " id="tab_5">
								<div class="portlet-body form">
										<div class="form-group">
										<div class="col-md-12">
											<label class="control-label col-sm-2" style="text-align:center;">
												<button type="button" class="btn red delete">
													<i class="fa fa-barcode"></i>
													<span><?php echo $tr->translate("SCAN");?></span>	
												</button>
											</label>
											<label class="control-label col-sm-10">
												<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item_leave" name="add_item_leave" Onchange="getItemOrderLeaveProduct();getBlockBysite();getNoneProuduct();" >
												<?php //echo $this->items_leave; ?>
												</select>
											</label>
										</div>
										</div>
										<div class="portlet-body">
											<table class="table table-striped table-bordered table-hover" id="table_leave_product" style="font-size:12px;">
												<tr height="33px">
													<th><?php echo $tr->translate("DEL");?></th>
													<th><?php echo $tr->translate("NUM");?></th>
													<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
													<!--<th><?php echo $tr->translate("FREE");?></th>-->
													<th><?php echo $tr->translate("QTY_UNIT");?></th>
													<th><?php echo $tr->translate("QTY_PER_UNIT");?></th>
													<th><?php echo $tr->translate("QTY_ORDER");?></th>
													<th><?php echo $tr->translate("UNIT_PRICE_CAP");?></th>
													<th style="white-space:nowrap;"><?php echo $tr->translate("DISCOUNT");?></th>
													<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
													<th><?php echo $tr->translate("BLOCK");?></th>
													<th><?php echo $tr->translate("JOb");?></th>
											</tr>
										 </table>
										 <input type="hidden" id="leave_stock_identity" name="leave_stock_identity" />
												
									</div>
								</div>
							</div>
							<!-- Close Contant Tap Two-->
						</div>
						<!-- Close Contant Tap -->
						<!-- Block Price -->
						<div class="form-group">
							<label class="control-label col-md-2"></label>
							<div class="col-md-4">
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("តម្លៃសរុប​ :");?><span class="required"></span></label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("price_product");?>
								<?php echo $form->getElement("price_jobtype");?>
								<?php echo $form->getElement("totalAmoun");?>
								</div>
							</div>
						</div>					
						<div class="form-group">
							<label class="control-label col-md-2"></label>
							<div class="col-md-2"></div>
							<div class="col-md-2"></div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("dis_value");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"></label>
							<div class="col-md-4"></div>
							<label class="control-label col-md-2">សាច់ប្រាក់សរុប​ :<span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php //echo $form->getElement("paid");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("PAID");?><span class="required">
								 </span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>
							
							<label class="control-label col-md-1"><?php echo $tr->translate("BALANCE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-1">
								<div class="input-icon right">
								<?php echo $form->getElement("remain");?>
								</div>
							</div>
						</div>
						
						<!-- Close Block Price  -->
						<!-- Block Condition -->
						<div class="form-group">
						<div class="col-md-2">
							<button type="button" class="btn delete" style="width:100%; background:#65879A;">
									<strong style="color:#fff;"><?php echo $tr->translate("TERM_CONDITION");?></strong>
								</button>
						</div>
							<div class="col-md-10">
								<select data-placeholder="Select..." class="form-control select2me" id="term_item" name="term_item" Onchange="getTermItem();"  style="margin:0 auto; ">
										<?php echo $this->term_opt; ?>
								</select>
							</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_termcondition" style="font-size:12px;">
								<tr>
									<td width="80px;" align="center"><?php echo $tr->translate("DEL");?></td>
									<td width="70px" align="center"><?php echo $tr->translate("NUM");?></td>
									<td style="white-space:nowrap;"><?php echo $tr->translate("TERM_CONDITION");?></td>
								</tr>	
							</table>
						</div>
						<input type="hidden" id="identity_term" name="identity_term" />
						<!-- Close Condition -->
						<!--  Block bottum -->
						<div class="form-group">
							<div class="col-md-4">
								<a href="<?php echo $this->baseUrl();?>/sales/index/"><button type="button" class="btn blue btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-4">
								<div class="input-icon right">
									<button type="submit" class="btn blue btn-block btn-lg" name="save_new"  id="save_new"><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_NEW")?></button>
								</div>
							</div>
							<div class="col-md-4">
								<!--   <button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRINT")?> </button>-->
								 <button type="submit" id="saveprint"   name="saveprint"   onClick="getPriceProduct();doPrint();  printSubmit();" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRINT")?> </button>
							</div>
						</div>
						<!-- Close Block-->
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

 <!-- save print -->
 <div id="customer_receipt" class="modal fade" tabindex="-1" data-width="110px">
      <div class="modal-dialog" style="width: 65%;">
           <div class="modal-content" >
               <div class="portlet box blue ">
               		<div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                           
                           <div class="portlet-body form">
                   <form id="frmvendor" method="post" name="frmvendor">
                    <div class="form-body"   >
                      <div class="form-group"  >
					     <div id="divPrint" style="width: 23cm !important; height: 14cm ; padding: 0px; margin: 0px;">  
					           <style>
										#tds{
								           border:1px solid #000;
								        }
										.style{
											line-height: 20px;font-size: 9px !important;
											font-family: 'Khmer OS Battambang';
										}
										ul{margin: 0;padding:0;}
										table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
										ul.pur_info li{line-height:18px; 
												font-weight: normal !important;}
										ul.pur_info li strong{font-weight: bold;}
								       .hover:hover{background: #ccc;}
										label {
										    font-weight: bold;
										    font-size: 11px;
										}
								</style>
					           
					       <table  class="table_reciept" style="border-collapse: collapse;font-family:'Khmer OS Battambang';font-size: 11px !important; " width="100%;"  >
					             <tr >
					               <td  valign="top" style="padding-top: 0px;"> <img style="width:140px; " alt="No Images " src="<?php echo $this->baseUrl();?>/images/logo.jpg"></td>
				                   <td nowrap="nowrap" colspan="3" valign="bottom" ><h4 class="modal-title center" style="text-align:center; font-size:13px;font-weight:10px; font-size:13px;font-weight:bold; font-family:'Khmer MEF2'"><strong><?php echo $tr->translate("");?>
				                                     <br/><u><b >ប័ណ្ណបញ្ជាលក់ទំនិញ</b></u> 
				                                </strong></h4>
				                   </td>
				                   <td nowrap valign="top" style="padding-left:100px;">  
				                     <p class="modal-title center" ><strong></strong></p>
				                     <span style="text-align:center; font-size:13px;font-weight:bold; font-family:'Khmer MEF2'">ការដ្ខាន :<label id="lb_site"></label></span>
				                      
				                     <br/> <span style="color:red;"><label id="lb_sal_no"></label></span> 
				                   </td>
				               </tr>
				               <tr>
				                   <td colspan="5">
				                       <table  style="border-collapse: collapse;font-family:'Khmer OS Battambang';font-size: 11px !important;width:100%">
										  <tr>
										    <td width="20%"> </td>
										    <td width="20%"> </td> 
										    <td width="20%"> </td>
										    <td width="40%" style="border:1px solid #000;">ថ្ងៃបញ្ជារលក់ៈ  <label id="lb_order_date"></label> 
										    <br/> Sale No : <label id="lb_sale_no"></label>
										    <br/> គោលដៅទទួលទំនិញៈ  <label id="lb_go_site"></label> 
										    </td>
										  </tr>
										</table> 		 
				                   </td>
				               </tr>
				               <tr>
				                  <td colspan="5">
				                  	   <table id="table_product_price" class="table_reciept" style="border-collapse: collapse;font-family:'Khmer OS Battambang';font-size: 11px !important;" width="100%">
				                  	           <tr align="center">
								                   <td style=" border:1px solid #000;width:3px;" nowrap >ល.រ <br/>No.</td>
								                   <td id="tds" nowrap>បរិយាយ <br/>Description</td>
								                   <td id="tds" nowrap>ចំនួន <br/>Quantity</td>
								                   <td id="tds" nowrap>តម្លៃរាយ <br/>Unit Price</td>
								                   <td style=" border:1px solid #000;width:160px;" nowrap >តម្លៃសរុប <br/>Amount</td>
								               </tr>
								               
				                  	   </table>
				                  </td>
				               </tr> 
				               <tr>
				                   <td colspan="5">
				                       
				                   </td>
				               </tr>
				               <tr>
				                   <td colspan="5">
				                       <table id="table_condition" class="table_reciept" style="border-collapse: collapse;font-family:'Khmer OS Battambang';font-size: 11px !important;" width="100%">
				                  	          
				                  	   </table>
				                   </td>
				               </tr>
				               <tr>
				                   <td colspan="4"></td>
				                   <td style="font-size:13px;font-weight:bold;text-align: right;" nowrap="nowrap" >ភ្នំពេញ, ថ្ងៃ ទី    <label id="lb_day"></label>&nbsp; ខែ &nbsp;<label id="lb_month"></label>&nbsp;​ ឆ្នាំ &nbsp;<label id="lb_year"></label> <?php //echo 'កាលបរិច្ឆេទ Date:'.date("F j, Y, g:i a");?>
				                   </td>
				                </tr>
				                <tr>
				                   <td colspan="2" width="30%" style="font-size:13px;font-weight:bold;   " nowrap style="padding-left: 60px;" align="left">ស្នើរសុំដោយ </td>
				                   <td colspan="2" style="font-size:13px;font-weight:bold;   " align="center" width="30%">​ បញ្ជាទិញដោយៈ</td>
				                   <td  style="padding-right: 50px;font-size:13px;font-weight:bold;   " align="right" width="30%">អនុម័តដោយ</td>
				                </tr>
				                <tr><td style="height: 50px;"></td></tr>
				                <tr>
				                   <td colspan="2" width="30%" style=" " nowrap style="padding-left: 60px;" align="left">______________________</td>
				                   <td colspan="2" style=" " align="center" width="30%">​ ______________________</td>
				                   <td  style=" " align="right" width="30%">______________________</td>
				                </tr>
						       </table>
					        </div>
					        
					</div>
					<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
								   <button type="button" class="btn red" onclick="hideDialog();"><i class="fa fa-times"></i> បោះបង់/Cancel</button> 
								<!--  <button type="button" name="btnsprint" onclick="doPrint();printSubmit();" class="btn blue"><i class="fa fa-save"></i>បោះពុម្ព/Print</button>-->  
								</label>
					</div>
                                <!--     <label class="control-label"></label><input  id="btn_add" Onclick="addNewVendor()" type="button" class="btn default blue col-md-12" value="<?php echo $tr->translate("ADD_NEW");?>" />
                             
                                --> 
                       </div>
                     </form>
                    </div>
                 </div>
           </div>
        </div>
    </div>
   <input type="hidden" name="eee" value="3333" id="eee"/>
 </div>
 <!-- End Save Print -->
   
 <iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>

<script>
$('#frm').submit(function() {
	saleagent_id=$("#saleagent_id").val();
	if(saleagent_id=='' || saleagent_id==-1 || saleagent_id==0 ){
		alert("Please select vendor name");
		$('#saleagent_id').select2('open');
		return false;	
	}
 
});
</script>

<script>
////function get table list product invoid
function getPriceProductNoneStock(num_row){
	var identity = $('#leave_stock_identity').val();
	var arrays = identity.split(',');
	var index=0;
	var template = '';
	var title=1;
	//$('#table_product_price').html("");
	///setvalue to tabel 
	//setLabel();
	for(var i=0;i<arrays.length;i++) {index++;num_row++;
		// $('#a').text($("option:selected",$("#item_id_"+index)).text());
	    if(title !=1){
	    	template='<tr id="row_product_'+index+'" style="height:33px;border:1px solid #000;">';
			template+='<th style="border:1px solid blue;" width="4%">ល.រ<br/>No.</th>';
			template+='<th style="border:1px solid blue;" width="40%">បរិយាយ <br/>Description</th>';
			template+='<th style="border:1px solid blue;">ចំនួន <br/>Quantity</th>';
			template+='<th style="border:1px solid blue;">តម្លៃរាយ <br/>Unit Price</th>';
			template+='<th style="border:1px solid blue;">តម្លៃសរុប <br/>Amount</th>';
			template+="</tr>";
		    title=1;
		    $('#table_product_price').append(template);	
		    
	    }
		item_name=($("option:selected",$("#item_leave_id_"+index)).text());
		qty=$("#qty_l_"+index).val();
		price=$("#price_l_"+index).val();
		total=$("#total_l_"+index).val();
		pro_id=$("#pro_type_"+index).val();
		label_l=$("#label_l_"+index).val();
		    template='<tr id="row_product_'+index+'" style="height:33px;border:1px solid #000;">';
			template+='<td style="border:1px solid #000;text-align:center;" width="2%">'+num_row+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">'+item_name+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">'+qty+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;"> &nbsp;&nbsp;m<sup>3</sup></td>';
			template+='<td style="border:1px solid #000;text-align:center;">$&nbsp;&nbsp;'+price+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">$&nbsp;&nbsp;'+total+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">&nbsp;&nbsp;​</td>';
			template+="</tr>";
			if(identity !=""){
				$('#table_product_price').append(template);	
			}
	}
}
function getPriceProduct(){
	setLabel();
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	var index=0;
	var template = '';
	var title=0;
	$('#table_product_price').html("");
	///setvalue to tabel 
	//setLabel();
	
	for(var i=0;i<arrays.length;i++) {index++;
		// $('#a').text($("option:selected",$("#item_id_"+index)).text());
	    if(title !=1){
	    	template='<tr id="row_product_'+index+'" style="height:33px;border:1px solid #000;">';
			template+='<th style="border:1px solid #000;" width="4%">ល.រ</th>';
			template+='<th style="border:1px solid #000;" width="40%">ឈ្មោះទំនិញ</th>';
			template+='<th style="border:1px solid #000;">បរិនមាណ</th>';
			template+='<th style="border:1px solid #000;" width="5%">ឯកតា ​</th>';
			template+='<th style="border:1px solid #000;" width="20%">តម្លៃដើម ​</th>';
			template+='<th style="border:1px solid #000;" width="15%">តម្លៃសរុប​</th>';
			template+='<th style="border:1px solid #000;" width="15%">ផ្សេងៗ ​</th>';
			template+="</tr>";
		    title=1;
		    $('#table_product_price').append(template);	
	    }
		item_name=($("option:selected",$("#item_id_"+index)).text());
		qty=$("#qty"+index).val();
		price=$("#price"+index).val();
		total=$("#total"+index).val();
		pro_id=$("#pro_type_"+index).val();
		    template='<tr id="row_product_'+index+'" style="height:33px;border:1px solid #000;">';
			template+='<td style="border:1px solid #000;text-align:center;" width="2%">'+index+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">'+item_name+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">'+qty+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">&nbsp;&nbsp;</td>';
			template+='<td style="border:1px solid #000;text-align:center;">$&nbsp;&nbsp;'+price+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">$&nbsp;&nbsp;'+total+'</td>';
			template+='<td style="border:1px solid #000;text-align:center;">&nbsp;&nbsp;​</td>';
			template+="</tr>";
			if(identity !=""){
			  $('#table_product_price').append(template);	
			}
			var num=index;
	}
	getPriceProductNoneStock(num);
	 
	template='<tr id="row_product_'+index+'">';
	template+='<td colspan="4"></td>';
	template+='<td style="border:1px solid #000;text-align:right;">ទឹកប្រាក់សរុប /Subtotal</td>';
	template+='<td  colspan="2"​ style="border:1px solid #000;">&nbsp;&nbsp;$&nbsp;&nbsp'+$("#totalAmoun").val()+'</td>';
	template+="</tr>";
	$('#table_product_price').append(template);
	template='<tr id="row_product_'+index+'">';
	template+='<td colspan="4"></td>';
	template+='<td style="border:1px solid #000;text-align:right;">ទឹកប្រាក់បានទូទាត់ /Paid</td>';
	template+='<td  colspan="2"​ style="border:1px solid #000; ">&nbsp;&nbsp;$&nbsp;&nbsp;'+$("#paid").val()+'</td>';
	template+="</tr>";
	$('#table_product_price').append(template);
	template='<tr id="row_product_'+index+'">';
	template+='<td colspan="4"></td>';
	template+='<td style="border:1px solid #000;text-align:right;">ទឹកប្រាក់នៅសល់ ​ /Balance</td>';
	template+='<td colspan="2"​ style="border:1px solid #000; ">&nbsp;&nbsp;$&nbsp;&nbsp;'+$("#remain").val()+'</td>';
	template+="</tr>";
	$('#table_product_price').append(template);
	//getConditon();
	
}

//function set lable 
function setLabel(){
	//date 
	var date = new Date();
	day =("0" + date.getDate()).slice(-2);
	year = date.getFullYear();
	month=("0" + (date.getMonth() + 1)).slice(-2);
	$('#lb_day').text(day);
	$('#lb_month').text(month);
	$('#lb_year').text(year);
	 
	 $('#lb_site').text($("option:selected",$("#branch_id")).text());
	 $('#lb_order_date').text(getSetdate($("#order_date").val()));
	 $('#lb_sale_no').text($("#txt_order").val());
	 $('#lb_go_site').text($("option:selected",$("#branch_id")).text());
	 $('#lb_date_now').text(getSetdate(date));
}
///fucntion date 
function getSetdate(date){
	var today = new Date(date);
	var dd = today.getDate();
	var mm = today.getMonth()+1; //January is 0!

	var yyyy = today.getFullYear();
	if(dd<10){
	    dd='0'+dd;
	} 
	if(mm<10){
	    mm='0'+mm;
	} 
	var today='';
	return today = dd+'/'+mm+'/'+yyyy;
}
</script>

<script>
$(document).ready(function() {
	getProuductInstock();
	getNoneProuduct();
});
function popupProduct(){
	$('#productpopup').modal('show');
}
///ajax select fileter block by site  
<?php $url_block = $this->url(array('module'=>'sales','controller'=>'index','action'=>'getblock')); ?>
function getBlockBysite(){
	branch_id = $("#branch_id").val();
	$.ajax({
        url: "<?php echo $url_block;?>",
        type: "post",
        data:{'branch_id':branch_id},
        success: function(data){
	     so = $.parseJSON(data);
		        var identity = $('#leave_stock_identity').val();
			 	var arrays = identity.split(',');
			 	for(var k=1;k<=arrays.length;k++){
				 	
			 		 if(so !=""){
			 		  $('option', '#block_id_l_'+k).remove();
				 	  for(i=0;i<so.length;i++){  
					  		 $('#block_id_l_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].name));                   
						  	 $("#block_id_l_"+k).select2();
					  }
			 		}else{
			 			$('option', '#block_id_l_'+k).remove();
			 			$('#block_id_l_'+k).append('<option value="-1">Add New Block</option>');
			 			$("#block_id_l_"+k).select2();
			 		 	
			 		}
			 	}
        },
        error:function(){
           
        }
    });	
	//getBlockBysites();
}
<?php $url_blocks =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getblock')); ?>
function getBlockBysites(){
		branch_id = $("#branch_id").val();
		$.ajax({
	        url: "<?php echo $url_blocks;?>",
	        type: "post",
	        data:{'branch_id':branch_id},
	        success: function(data){
		    so = $.parseJSON(data);
			        var identity = $('#identity').val();
				 	var arrays = identity.split(',');
				 	for(var k=1;k<=arrays.length;k++){

				 		//alert(k);
					 	
				 		if(so !=""){
							$('option', '#block_id_'+k).remove();
							for(i=0;i<so.length;i++){  
						  		$('#block_id_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].name));                   
							  	$("#block_id_"+k).select2();
							}
				 		}else{
				 			$('option', '#block_id_'+k).remove();
				 			$("#block_id_"+k).select2();
				 		 	$('#block_id_'+k).append('<option value="-1">Add New Block</option>');
				 		}
				 	}
	        },
				error:function(){  
	        }
	    });	
		//getBlockBysite();
}


var index5 = 0;num=0;
var option5 = '<?php //echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
//var index=1;
function addRow(item_id) {
	index5++; //var first = index5;

	var identity = $('#identity').val();
	var arrays = identity.split(',');
	
	for(var i=0;i<arrays.length;i++) {
		i++;
	}
	
	//index=index+1;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+i+'</td>';
	template+='<td width="20%"><select class="form-control select2me" Onchange="ShowPopupProduct('+index5+');" id="item_id_'+i+'" name="item_id_'+i+'" > <option>'+getProuductInstock()+'</option></select>'+inp+'</td>';
	template+='<td><input style="background:#f5e1e1;" readonly type="text" class="form-control" id="current_qty'+index5+'" name="current_qty'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_'+index5+'" name="qty_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQty('+index5+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')"  required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+='<td width="10%"><select class="form-control select2me"  id="block_id_'+index5+'" name="block_id_'+index5+'" ><option>'+getBlockBysites()+'</option></select>'+inp+'</td>';
	
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);

	getQtyById(index5);
	 $("#item_id_"+index5).select2();
	 $("#block_id_"+index5).select2();
	$("#row_order_0").remove();
}

///funciton add row leave product 
var index = 0;num=0;
var option6 = '<?php echo $this->items_leave; ?>';
var job='<?php echo $this->jobtype; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
 
function addRowLeave(item_id) {
	index++; //var first = index5;
	 
	for(i=1; i<index; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
	}
	template='<tr id="row_order_leave_'+index+'" style="height:33px;">';
	var inp = '';
	if(index == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecordLeave('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="2%">'+index+'</td>';
	template+='<td width="20%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index + ');" id="item_leave_id_'+index+'" name="item_leave_id_'+index+'" ><option> </option></select>'+inp+'</td>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" required="1" value="1" id="qty_unit_l_'+index+'" name="qty_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" onkeyup="totalQtys('+index+')" class="validate[required,custom[number]] input form-control" value="0" id="qty_per_unit_l_'+index+'" name="qty_per_unit_l_'+index+'" /></td>';
	template+='<td ><input type="text" readonly onkeyup="calculatePriceLeave('+index+')" class="form-control" required="1" id="qty_l_'+index+'" name="qty_l_'+index+'"/></td>';
	template+='<td ><input type="text" onkeyup="calculatePriceLeave('+index+')" required="1" class="validate[required,custom[number]] input form-control" id="price_l_'+index+'" name="price_l_'+index+'" /></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePriceLeave('+index+')" value="0" id="dis_value_l_'+index+'" name="dis_value_l_'+index+'" class="form-control" /></td>';
	template+='<td ><input type="text" class="form-control" readonly="readonly" id="total_l_'+index+'" name="total_l_'+index+'" /></span></td>';
	template+='<td width="10%"><select class="form-control select2me"  id="block_id_l_'+index+'" name="block_id_l_'+index+'" ><option>'+getBlockBysites()+'</option></select>'+inp+'</td>';
	template+='<td width="10%"><select class="form-control select2me"   id="job_id_'+index+'" name="job_id_'+index+'" ><option>'+job+'</option></select>'+inp+'</td>';
	template+="</tr>";
	$('#table_leave_product').append(template);
	if($('#leave_stock_identity').val()!="") {
		var identity = $('#leave_stock_identity').val();
		$('#leave_stock_identity').val(identity+','+index);
	} else {$('#leave_stock_identity').val(index);}
	$("#item_leave_id_"+index).val(item_id);

	getQtyByIds(index);
	$("#block_id_l_"+index).select2();
	 $("#item_leave_id_"+index).select2();
	 
	 $("#job_id_"+index).select2();
	$("#row_order_leave_0").remove();
}
<?php $url_qty =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyById(index){
				item_id=$("#item_id_"+index).val();
				qty_unit=$("#qty_unit_"+index).val();
				qty_per_unit=$("#qty_per_unit_"+index).val();
				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							item_qty = $.parseJSON(data);			
							main_qty =$("#qty_unit_"+index).val();
							detail_qty =  $("#qty_per_unit_"+index).val();
							$("#current_qty"+index).val(item_qty.qty);
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty"+index).val(total_qty.toFixed(3));
						},
						error:function(e){
							//alert(e);
						}
				});
			}
}

///get qty set order qty 
<?php $url_qty =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getqtybyid')); ?>
function getQtyByIds(index){//use
			item_id=$("#item_leave_id_"+index).val();
				qty_unit=$("#qty_unit_l_"+index).val();
				qty_per_unit=$("#qty_per_unit_l_"+index).val();
				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				if(qty_unit==null || qty_unit==""){
					if(qty_per_unit!==null && qty_per_unit!==""){
						$("#qty_l_"+index).val(qty_per_unit);
					}
				}else{
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							item_qty = $.parseJSON(data);			
							main_qty =$("#qty_unit_l_"+index).val();
							detail_qty =  $("#qty_per_unit_l_"+index).val();
							$("#current_qty_l_"+index).val(item_qty.qty);
							total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							$("#qty_l_"+index).val(total_qty.toFixed(3));
							
							//getProductPrice(item_id,index);
						},
						error:function(e){
							//alert(e);
						}
				});
			}
}

function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		$('#productpopup').modal('show');
	}
	addRow(item_ids);
	$("#add_item").val("");
}
///function leave product 
function getItemOrderLeaveProduct(){
	 
	item_ids=$("#add_item_leave").val();
	$('#add_item_leave').val('').trigger("liszt:updated");
	if(item_ids==-1){
		$('#productpopup').modal('show');
	}
	addRowLeave(item_ids);
	$("#add_item_leave").val("");
}

var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	 
	netTotal();
	 
}
function setValueItemControll(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var k=1;k<=arrays.length;k++){
		//if(arrays[i] == index) arrays.splice(i,1);
		$('#item_id_'+k).append($("<option></option>").attr("value",k));
	}
}

function deleteRecordLeave(index) {
	var identity = $('#leave_stock_identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#leave_stock_identity').val(strings);
	$("#row_order_leave_"+index).remove();
	netTotal();
 
}

function netTotal() {//use
	var cur_type = $('#currency').val();
	
	var netTotal=0;
	var rowId = $('#identity').val();
	if(rowId !=''){
		var rowIDArray = rowId.split(',');
		var status = $('#status').val();
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += Number($('#total'+rowIDArray[n]).val());
		}
	}else{
		netTotal=0;
	}
	
	///sum total amount type job 
	var netTotals=0;
	var rowIds = $('#leave_stock_identity').val();
	if(rowIds!=''){
		var rowIDArrays = rowIds.split(',');
		var status = $('#status').val();
		for(var n = 0; n < rowIDArrays.length; n++) {
			netTotals += Number($('#total_l_'+rowIDArrays[n]).val());
		}
	}else{
			netTotals=0;
	}
	var result =(parseFloat(netTotal)+parseFloat(netTotals));
	$('#totalAmoun').val(result.toFixed(2));
	$("#price_product").val(netTotal.toFixed(2));
	$("#price_jobtype").val(netTotals.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = $('#dis_value').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
	$('#paid').val(totalpayment);
		doRemain();
}
///calcual leave discount 
function netTotals() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#leave_stock_identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total_l_'+rowIDArray[n]).val());
	}
	$('#totalAmoun_l').val(netTotal.toFixed(2));
	calculateDiscounts();
}
function calculateDiscounts(){//use
	var discountValue = $('#dis_value_l').val();
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun_l").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total_l').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun_l").val();
				totalpayment = alltotal - discountValue;
				$('#all_total_l').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun_l").val();
		totalpayment = alltotal - 0;
		$('#all_total_l').val(totalpayment);
	}
	$('#paid_l').val(totalpayment);
		doRemains();
}
function CalcualteTax() {
	$('#status').val();
}
function doRemain() {
	var all_total = parseFloat($('#all_total').val());
	var paid = parseFloat($('#paid').val());
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}
	
}
function doRemains() {
	var all_total = parseFloat($('#all_total_l').val());
	var paid = parseFloat($('#paid_l').val());
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain_l').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain_l').val(remain.toFixed(2));
	}
}

function totalQty(index){
	calculatePrice(index);
	//getQtyById(index);
	doOrderQty(index);
	$("#price"+index).val('');
}

///function get qty can not bigger request approve 
function doOrderQty(index) {
	var current_qty = parseFloat($('#current_qty'+index).val());
	var qty_unit = parseFloat($('#qty_unit_'+index).val());
	var qty_per_unit = parseFloat($('#qty_per_unit_'+index).val());
	var qty_total=qty_unit+qty_per_unit;
	
	if( qty_total>current_qty ){
		 alert(" Value Qty order can not biger then total Curr Qty  !");
		 $('#qty_per_unit_'+index).val('0.00');
		 $('#qty_unit_'+index).val('0.00');
		 $('#qty'+index).val('0.00');
   }else{
	   getQtyById(index);
	}
}

///qty leave product 
function totalQtys(index){
	calculatePriceLeave(index);
	getQtyByIds(index);
	$("#price_l_"+index).val('');
}
function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));		
		}
		netTotal();
}
///function get price live 
function calculatePriceLeave(index) {
	var qty = $('#qty_l_'+index).val();
	var price = $('#price_l_'+index).val();
	var total = price * qty;	
	var ds = $('#dis_value_l_'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total_l_'+index).val(after_discount.toFixed(2));
		}else{
		
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value_l_'+index).val(0);
				after_discount = total;
			}
			$('#total_l_'+index).val(parseFloat(after_discount).toFixed(2));
		}
	}else{
		$('#total_l_'+index).val(parseFloat(total).toFixed(2));		
		}
	//netTotals();
	netTotal();
}

 var record_id = 1;
function ShowPopupProduct(product_id){
	item_id = $("#item_id_"+ product_id).val();
	record_id = product_id;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(product_id);
	}
}
function AddLocation(){
	var location_id= $("#LocationId").val();
	if(location_id==-1){
		$('#popup_location').modal('show');
	  }	
}
<?php $url_add_location =  $this->url(array('module'=>'product','controller'=>'index','action'=>'add-new-location')); ?>
function addNewLocation(){
	var location_name = $("#StockName").val();
	var ContactName   = $("#ContactName").val();
	var ContactNumber = $("#ContactNumber").val();
	var location_add  = $("#location_add").val();
	var remark_add    = $("#description").val();
	validate_text('#StockName');
	$.ajax({
        url: "<?php echo $url_add_location;?>",
        type: "post",
        data: {'location_name':location_name,'ContactName':ContactName,'ContactNumber':ContactNumber,'location_add':location_add,'remark_add':remark_add},
        success: function(data){
           val = $.parseJSON(data);
            $('#LocationId').append($("<option></option>").attr("value",val['LocationId']).attr("selected",true).text(location_name)); 
            document.getElementById("frm-location").reset();
            HideDialoglocation();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
function getTermItem(){
	termid=$("#term_item").val();
	$('#term_item').val('').trigger("liszt:updated");
	if(termid==-1){
		return false;
	}
	addtermcondition(termid);
	$("#term_item").val("");
}
term_option = '<?php echo $this->term_opt; ?>';
index1 = 0;
var index = 0;num=0;
var option6 = '<?php echo $this->items_leave; ?>';
var job='<?php echo $this->jobtype; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
function addtermcondition(t_id){
	index1++; 
	template='<tr id="row_term_'+index1+'" style="height:33px;">';
    template+='<td width="20px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td  width="2%">'+index1+'</td>';
	template+='<td><select class="form-control select2me" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_option+'<option></option></select></td>';
	template+="</tr>";
	$('#table_termcondition').append(template);
	if($('#identity_term').val()!="") {
		var identity = $('#identity_term').val();
		$('#identity_term').val(identity+','+index1);
	} else {$('#identity_term').val(index1);}
	$("#termid_"+index1).val(t_id);
	$("#row_term_0").remove();	
}
function deleteTermRecord(termid){
	var identity = $('#identity_term').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == termid) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_term').val(strings);
	$("#row_term_"+termid).remove();
}
///ajax select product by location   
<?php $url_product =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'get-product-instock')); ?>
 
function getProuductInstock(){
	   //alert(type);
	    branch_id = $("#branch_id").val();
		$.ajax({
	        url: "<?php echo $url_product;?>",
	        type: "post",
	        data:{'branch_id':branch_id},
	        success: function(data){
		     so = $.parseJSON(data);
				 	$('option', '#add_item').remove();
				 	$("#add_item").select2();
				 	for(i=0;i<so.length;i++){  
				  		 $('#add_item').append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].item_name));
					  	 $("#add_item option[value='0']").attr("selected","selected");
						 $("#add_item").select2();
				   }
					//$("#add_item").val(0);
				 	var identity = $('#identity').val();
					var arrays = identity.split(',');
				 	for(var k=1;k<=arrays.length;k++){
				 		 $('option', '#item_id_'+k).remove();
				 		 $("#item_id_"+k).select2();
				 		 if(so !=""){
					 	  for(i=0;i<so.length;i++){  
						  		 $('#item_id_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].item_name));                   
							  	 $("#item_id_"+k).select2();
						  }
				 		}
					 		totalQty(k);
				 	}
	        },
	        error:function(){
	        }
	    });	
		//getBlockBysite();
}

///ajax select none product by location   
<?php $url_product =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'get-product-nonestock')); ?>
 
function getNoneProuduct(){
	   //alert(type);
	    branch_id = $("#branch_id").val();
		$.ajax({
	        url: "<?php echo $url_product;?>",
	        type: "post",
	        data:{'branch_id':branch_id},
	        success: function(data){
		     so = $.parseJSON(data);
				 	$('option', '#add_item_leave').remove();
				 	$("#add_item_leave").select2();
				 	for(i=0;i<so.length;i++){  
				  		 $('#add_item_leave').append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].item_name));
					  	 $("#add_item_leave option[value='0']").attr("selected","selected");
						 $("#add_item_leave").select2();
						 
				   }
					 
				 	var identity = $('#leave_stock_identity').val();
					var arrays = identity.split(',');
				 	for(var k=1;k<=arrays.length;k++){
				 		$('option', '#item_leave_id_'+k).remove();
				 		 $("#item_leave_id_"+k).select2();
				 		 if(so !=""){
					 	  for(i=0;i<so.length;i++){  
						  		 $('#item_leave_id_'+k).append($("<option></option>").attr("value",so[i].id).attr("selected",true).text(so[i].item_name));                   
							  	 $("#item_leave_id_"+k).select2();
						  }
				 		}
				 	}
	        },
	        error:function(){
	        }
	    });	
		//getBlockBysite();
}

function printSubmit(){
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		price =$("#price"+1).val();
		if(price==''){
			alert("Please input  price");
			//$('#price1').text('open');
			return false;
		}else{
			 document.getElementById('frm').submit();
		}
	}
}

function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
  
}
</script>	