<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'category','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'category','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'category','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("CATEGORY_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("CATEGORY_LIST");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="">
								<!--  <div class="col-md-3">
									<?php //echo $formFilter->getElement('name');?>
								</div>-->
												
								<div class="col-md-3">
									<?php echo $formFilter->getElement('parent');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('status');?>
								</div>
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
				</div>
			</form>
			</div>
			<div class="portlet-body">
						<?php echo $this->list;?>
							
						</div>
	</div>
