<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
//$frm = $this->frm_income;
?>
<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'otherincome','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'otherincome','action'=>'index'));
	$frm = $this->frm_income;
?>
<title><?php echo $tr->translate("ADD_INCOME");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_INCOME")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_NO")?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm->getElement('invoice');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("INCOME_TITLE")?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $frm->getElement('title');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CURRENCY_TYPE")?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $frm->getElement('currency_type'); ?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("TOTAL_INCOME")?>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $frm->getElement('total_amount');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $frm->getElement("branch_id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE")?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i><?php echo $frm->getElement('Date');?></div>
							</div>
						</div>
						<div class="form-group" >
						    <label class="control-label col-md-2"><?php echo $tr->translate("NOTE")?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $frm->getElement('Description');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("STATUS")?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $frm->getElement('Stutas');?>
								</div>
							</div>
							
						</div>
						
						
						<div class="form-group">
						    <div class="col-md-4">
								<a href="<?php echo $this->baseUrl();?>/purchase/otherincome/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-4">
								<div class="input-icon right">
									<button type="submit" name="btnsave_close" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-4">
								<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div id="productpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">   
		<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_INCOME_TITLE");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php //echo $url_new;?>" >
						 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmtitle" name="frmtitle" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3"><?php echo $tr->translate("TITLE");?><span class="required">
								</span>
							</label>
							<div class="col-md-9">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="income_title" id="income_title" class="validate[required] form-control" placeholder="Enter Name EN" style="height:40px;" rows="24" cols="80"></textarea>
								</div>
							</div>
						</div>
						<!--  <div class="form-group">
							<label class="control-label col-md-3"><?php //echo $tr->translate("PARENT_TITLE");?><span class="required">
								</span>
							</label>
							<div class="col-md-9">
								<div class="input-icon right">
									<i class="fa"></i>
									<select readonly="readonly" name="parent_id_title" id="parent_id_title" class="form-control" placeholder="Please select Category" >
									    <option value="1" label="INCOME" ><?php //echo $tr->translate("INCOME");?></option>
									    <?php //echo $this->rs["parent_id_title"];?>
									</select>
								</div>
							</div>
						</div>-->
					<div class="form-group">
						<label  class="col-md-12 col-md-offset-4 col-md-8">
							<button type="button" name="btnsavenew" Onclick="addotherincome();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRODUCT")?> </button>
						</label>
					</div>
				</div>
				</form>
			   </div>
		     </div>
	        </div>
          </div>
          </div>
        </div>
    </div>
 </div>
<script>
function showincome(){
	title = $("#title").val();
	
	if(title==-1){
	$('#productpopup').modal('show');
	}
	
}

<?php $url_add_new =  $this->url(array('module'=>'purchase','controller'=>'expensetitle','action'=>'addajaxtitleincome')); ?>
function addotherincome(){
		title_id = $("#income_title").val();
		$.ajax({
	        url: "<?php echo $url_add_new;?>",
	        type: "post",
	        data: $('#frmtitle').serialize(),
	        success: function(data){
		      data = $.parseJSON(data);
		      //alert(data);
		      $('#title').append($("<option></option>").attr("value",data['id']).attr("selected",true).text(title_id));                       
			  $("#title").select2();
		      $('#productpopup').modal('hide');
			 
	        },
	        error:function(){
	           
	        }
	    });	
}
</script>