<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_purchase=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-purchase'), null, true);
  $rpt_purcahsedetail=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-purchaseitem'), null, true);
  $rpt_sale=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-sales'), null, true);
  $rpt_saledetail=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-saleitem'), null, true);
  $rpt_customer=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-customer'), null, true);
  $rpt_saleperson=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-saleperson'), null, true);
   $rpt_expense = $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-expense'), null, true);
   $rpt_income = $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-income'), null, true);
   $rpt_grand=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-grand'), null, true);
   $sale_quotation_report=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-quotationissue'), null, true);
   $invoice_and_delivery=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-delivery'), null, true);
   //$income_expense=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-typeexpense'), null, true);
   $vandor_balance=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-vandorbalance'), null, true);
   $chque_withdrawal=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-chequewithdrawal'), null, true);
   $rpt_receive=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-receive'), null, true);
   
   $user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
	 $level = $result["level"];
	// echo $level;
  
  ?>
<div class="row">
<?php if( $level==1 or  $level==8){//work?>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_purchase;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("PURCHASE_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_purchase;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_purcahsedetail;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("REPORT_LIST_PURCHASE_DETAIL");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_purcahsedetail;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_sale;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("SALE_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_sale;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
	<?php }?>
	<?php if($level==1 OR $level==2 OR  $level==3 OR $level==5 OR $level==6 OR $level==10){?>
			<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $sale_quotation_report;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("SALE_QUOTATION_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $sale_quotation_report;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saledetail;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("REPORT_LIST_SALE_DETAIL");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_saledetail;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_receive;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("REPORT_RECEIVE");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_receive;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $invoice_and_delivery;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("INVOICE_DELIVERY");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $invoice_and_delivery;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_customer;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("CUSTOMER_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_customer;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saleperson;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("SALE_PERSON_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_saleperson;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
		
		
		<?php //if( $level==1 or  $level==2 or  $level==3 or  $level==6 or  $level==8 or  $level==10){?>
		<?php //if( $level==1 OR $level==2 OR $level==3 OR $level==9 OR $level==10){// admin /sale finance?>
				<?php }?>
				<?php if( $level==1 or  $level==8){//work?>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_expense;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("EXPENS_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_expense;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_income;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("INCOME_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_income;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $rpt_grand;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 <?php echo $tr->translate("GRAND_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php //echo $income_expense;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php //echo $tr->translate("TYPE_EXPENS_REPORT");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php //echo $income_expense;?>">
						<?php //echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>-->
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $vandor_balance;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("SUPPLIYER_BALANCE");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $vandor_balance;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $chque_withdrawal?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 <?php echo $tr->translate("CHQUE_WITHDRAWAL");?>
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $chque_withdrawal?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
			</div>
			<?php }?>		