<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
//$brach_name =  $this->branch;
?>
<title><?php echo $tr->translate("RECEIVE_REPORT");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RECEIVE_REPORT");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   <?php echo $tr->translate("ACTION");?> <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("REPORT_EXCEL");?> </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->formFilter; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("BOREY_PHNOM_PENH_THMEY");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RECEIVE_REPORT");?></li>
		                			<!--  <li style="text-align:center; font-size:13px;"><?php //echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php //echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>-->
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr>
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		           
		             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                <tbody><tr height="30px;" bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("RECEIVE_NO");?></td>
							<td><?php echo $tr->translate("BRANCH_NAME");?></td>
							<td><?php echo $tr->translate("VENDOR_NAME");?></td>
							<td><?php echo $tr->translate("CURRNECY_TYPE");?></td>
							<td><?php echo $tr->translate("ORDER");?></td>
							<td><?php echo $tr->translate("INVOICE_NO");?></td>
							<td><?php echo $tr->translate("ORDER_DATE");?></td>
							<td><?php echo $tr->translate("DATE_IN");?></td>
							<td><?php echo $tr->translate("TOTAL_AMOUNT");?></td>
							<td><?php echo $tr->translate("DISCOUNT");?></td>
							
							<td><?php echo $tr->translate("TOTAL");?></td>
							<td><?php echo $tr->translate("PAID");?></td>
							<td><?php echo $tr->translate("BALANCE");?></td>
							<td><?php echo $tr->translate("TOTAL_IN_STOCK");?></td>
							<td><?php echo $tr->translate("TOTAL_LEAVE_STOCK");?></td>
							<!--<td><?php //echo $tr->translate("PURCHAES_STATUS");?></td>
							<td><?php //echo $tr->translate("RECEIVE_STATUS");?></td>-->
							<td><?php echo $tr->translate("STATUS");?></td>
							<td><?php echo $tr->translate("BY_USER");?></td>
		                </tr>
						<?php $num=1;//print_r($this->receives);
							  $all_totals=0;
							  $all_paid=0;
							  $all_balance=0;
						 if(!empty($this->receives))foreach ($this->receives AS $index=>$rs){
						?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/receivedetail/id/".$rs["order_id"];?>">&nbsp;<?php echo $rs["recieve_number"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/receivedetail/id/".$rs["order_id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/receivedetail/id/".$rs["order_id"];?>">&nbsp;<?php echo $rs["vendor_name"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["curr_name"];?></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/receivedetail/id/".$rs["order_id"];?>">&nbsp;<?php echo $rs["order_number"];?></a></td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/receivedetail/id/".$rs["order_id"];?>">&nbsp;<?php echo $rs["invoice_no"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_order"]));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_in"]));?></td>
						   
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["all_total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["discount_value"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["net_total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["paid"],2);?></td>
						   <td>&nbsp;<?php echo number_format($rs["balance"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["sub_total_product"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["sub_total_jobtype"],2);?></td>
						   <!--<td>&nbsp;<?php //echo $rs["purchase_status"];?></td>
						   <td>&nbsp;<?php //echo $rs["recieve_status"];?></td>-->
						   <td>&nbsp;<?php echo $rs["STATUS"];?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						</tr>
						    <?php 
							  $all_totals=$all_totals+$rs["net_total"];
							  $all_paid=$all_paid+$rs["paid"];
							  $all_balance=$all_balance+$rs["balance"];
							?>
						 <?php }?>
		               </tbody>
		             </table>
		              <br>
					  <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                <tbody><tr height="30px;" bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
		                    <td><?php echo $tr->translate("All_TOTALS");?></td>
							<td><?php echo $tr->translate("All_PAID");?></td>
							<td><?php echo $tr->translate("All_BALANCE");?></td>
							</tr>
							<tr align="center">
							    <td style="white-space: nowrap;"><?php echo number_format($all_totals,2);?></td>
								<td style="white-space: nowrap;"><?php echo number_format($all_paid,2);?></td>
								<td style="white-space: nowrap;"><?php echo number_format($all_balance,2);?></td>
							</tr>
						</tbody>
                      </table>						
					  <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate("APPROVED BY");?></th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate("VERIFIED_BY");?></th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate("PREPARED_BY");?></th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
