<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('INCOME_REPORT')); 
	echo $this->headTitle();
	
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$originalDate = "2012-10-31";
	$newDate = date("m/d/Y", strtotime($originalDate));
?>
<form  id='foundation_class' action=""  method="post" enctype="application/x-www-form-urlencoded">
</form>
<style>
.hover:hover{ background: #ddd;}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("INCOME_REPORT");?>
				</div>
					<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   <?php echo $tr->translate("ACTION");?> <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("REPORT_EXCEL");?> </a>
									</li>
								</ul>
					</div>
			</div>
			 <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->formFilter; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('title_in');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
			</div>
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint"  >
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Hanuman';">
							<tr style="font-size: 13px;">
							    <td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
								<td colspan="3" align="center">
								    <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate("BOREY_PHNOM_PENH_THMEY");?></strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate("INCOME_REPORT");?></strong><br />
									<!--  <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">For Date <?php //echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php //echo date("d-M-Y",strtotime($this->search["end_date"]));?></strong>-->
								</td>
							</tr>
							<tr>
								<td width="20%" align="left">
								</td>
								<td align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"></strong>
								</td>
								<td align="right" width="20%">&nbsp;</td>
							</tr>
							<?php 
								$total_income_kh=0;
								$total_income_dollar=0;
								$total =0;
								$total_paid =0;
								$total_expense_kh=0;
								$total_expense_dollar=0;
							?>
							<tr>
									<td colspan="3">
									<table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		            					<tr style="font-size:11px; height: 20px;border: 1px solid #000;white-space: nowrap;background-color: #ccc;line-height:30px;font-weight: bold;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $tr->translate('NUM')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('BRANCH_NAME')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('INCOME_TITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('NAME_ENTITLE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('INVOICE_NO')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('TOTAL')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('ACTUAL_PAYMENT_DATE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('NOTE')?></td>
											<td style="border: 1px solid #000;"><?php echo $tr->translate('USER')?></td>
										</tr>
										 
										 <style> td{padding:0 3px; }</style>
										 <?php //$income=$this->income;?>
									<?php $i=0;foreach($this->income as $row){ $i++;?>
										<tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
											<td style="border: 1px solid #000;"><?php echo $i;?></td>
											<td style="border: 1px solid #000;"><?php echo $row['branch_name'];?></td>
											<td style="border: 1px solid #000;text-align: left;"><?php echo $row['title'];?></td>
											<td align="canter" style="border: 1px solid #000;"><?php echo $row['title_en'];?></td>
											<td style="border: 1px solid #000;"><?php echo $row['invoice'];?></td>
											<td style="border: 1px solid #000;background:#c6e2fb"><?php echo number_format($row['total_amount'],2);?><?php if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?></td>
											<td style="border: 1px solid #000;"><?php echo date('d-M-Y',strtotime($row['for_date']));?></td>
											<td style="border: 1px solid #000;"><?php echo $row['desc'];?></td>
											<td style="border: 1px solid #000;font-size: 10px;"><?php echo $row['user_name'];?></td>
										</tr>
											<?php 
// 												if($row['curr_type']==2){
// 													$total_expense_kh = $total_expense_kh + $row['total_amount'];
// 												}else{
													$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
// 												}
											?> 
										 <?php } ?>
										 <tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
											<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="7"></td>
											<td style="border: 1px solid #000; white-space: nowrap;"><?php echo $tr->translate("GRAND_TOTAL"); ?></td>
											<td style="border: 1px solid #000;"><?php echo number_format($total_expense_dollar,2);?></td>
										</tr>
										</table>
									</td>
								</tr> </tbody>
		             </table>
								<br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate("VERIFIED_BY");?></th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate("PREPARED_BY");?></th>
						   </tr>
						</tbody>
					</table>
							
			</table>
	</div>	
	</div>
	</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
}

</script>
