<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'brand','action'=>'add',),null,true);
	$url_edit = $this->url(array('module'=>'product','controller'=>'brand','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'brand','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("BRAND_LIST");?></title>
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption col-md-10">
					<i class="fa fa-globe"></i><?php echo $tr->translate("BRAND_LIST");?>
			</div>
			<div class="col-md-2" style="text-align:right; margin-top: 4px;">
				<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div style="margin:0px auto;">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('name');?>
								</div>
												
								<label class="col-md-1 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('status');?>
								</div>
								<div class="col-md-2">
									<button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
								</div>
							</div>
				</div>
			</form>
		</div>
		<div class="portlet-body">
			<?php echo $this->list;?>
		</div>
	</div>
